# -*- coding: utf-8 -*-
"""model_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMj9rMh13rlXM_rrez-_HvF63AHuW8o-
"""

import json
from pathlib import Path
from collections import Counter
import random
import textwrap

import streamlit as st
import evaluate
import pandas as pd
from openai import OpenAI

# In Streamlit Cloud, define OPENAI_API_KEY in "App settings" -> "Secrets"
# OpenAI client – reads API key from Streamlit secrets
client = OpenAI(api_key=st.secrets.get("OPENAI_API_KEY", None))

# ===============================
# 1. DATA LOADING
# ===============================

@st.cache_data
def load_qa_data(path: str = "Q&A_db_practice.json"):
    data_path = Path(path)
    if not data_path.exists():
        st.error(f"Could not find {path}. Please make sure the file is in the same folder as model_app.py.")
        return []
    with open(data_path, "r", encoding="utf-8") as f:
        qa_items = json.load(f)
    return qa_items


qa_items = load_qa_data()

if not qa_items:
    st.stop()


# ===============================
# 2. AUTOMATIC EVALUATOR
# ===============================

# Initialize ROUGE metric
rouge = evaluate.load("rouge")


def compute_rouge_l(reference: str, prediction: str) -> float:
    """
    Compute ROUGE-L F1 score between reference and prediction.
    Returns a value between 0 and 1.
    """
    results = rouge.compute(
        predictions=[prediction],
        references=[reference],
        use_stemmer=True
    )
    return results["rougeL"]


def extract_keywords(text: str, min_len: int = 4, top_k: int = 20):
    """
    Extract simple keyword candidates: lowercase tokens with at least min_len chars,
    ranked by frequency (very naive but sufficient for this assignment).
    """
    tokens = [t.strip(".,;:!?()[]\"'").lower() for t in text.split()]
    tokens = [t for t in tokens if len(t) >= min_len]
    freq = Counter(tokens)
    most_common = [w for w, _ in freq.most_common(top_k)]
    return most_common


def keyword_coverage(reference: str, prediction: str, top_k: int = 20):
    """
    Compute coverage of important reference keywords in the student's prediction.
    Returns:
        coverage_ratio (0-1),
        present_keywords,
        missing_keywords
    """
    ref_keywords = extract_keywords(reference, top_k=top_k)
    pred_tokens = set(
        t.strip(".,;:!?()[]\"'").lower() for t in prediction.split()
    )

    present = [w for w in ref_keywords if w in pred_tokens]
    missing = [w for w in ref_keywords if w not in pred_tokens]

    coverage = len(present) / max(1, len(ref_keywords))
    return coverage, present, missing


def evaluate_answer(reference: str, student_answer: str) -> dict:
    """
    Main automatic evaluator:
    - Computes ROUGE-L
    - Computes keyword coverage
    - Produces numeric score (0-100)
    - Produces textual explanation
    """
    # 1. ROUGE-L (0-1)
    rouge_l = compute_rouge_l(reference, student_answer)

    # 2. Keyword coverage (0-1)
    coverage, present_kw, missing_kw = keyword_coverage(reference, student_answer)

    # 3. Combine the two into a score (simple linear combination)
    alpha = 0.5  # weight for ROUGE-L
    beta = 0.5   # weight for keyword coverage

    combined = alpha * rouge_l + beta * coverage
    score_0_100 = round(combined * 100, 1)

    # 4. Build explanation
    explanation_parts = []

    explanation_parts.append(
        f"ROUGE-L similarity: {rouge_l:.3f} (0–1 scale). "
        f"This reflects overlap in phrasing and sentence structure."
    )
    explanation_parts.append(
        f"Keyword coverage: {coverage:.3f} (0–1 scale). "
        f"This reflects how many core terms from the reference you mentioned."
    )

    if missing_kw:
        missing_str = ", ".join(missing_kw[:8])
        explanation_parts.append(
            f"Some important concepts not explicitly mentioned: {missing_str}."
        )
    if present_kw:
        present_str = ", ".join(present_kw[:8])
        explanation_parts.append(
            f"Key concepts you did mention: {present_str}."
        )

    explanation = " ".join(explanation_parts)

    return {
        "score": score_0_100,
        "rouge_l": rouge_l,
        "coverage": coverage,
        "present_keywords": present_kw,
        "missing_keywords": missing_kw,
        "explanation": explanation,
    }


# ===============================
# 3. OPTIONAL LLM-BASED EVALUATOR (STUB)
# ===============================

LLM_SYSTEM_PROMPT = """
You are an expert university-level Machine Learning professor.

The student answers conceptual ML questions. You must:

1. Compare the student's answer with the reference answer.
2. Judge correctness, completeness, and clarity.
3. Identify important missing or incorrect points.
4. Produce a numeric score from 0 to 100, where:
   - 90-100: Excellent, almost identical to reference.
   - 70-89: Good, covers most key ideas with minor gaps.
   - 40-69: Partial, some correct ideas but incomplete.
   - 0-39: Poor, mostly incorrect or missing key ideas.

You MUST respond ONLY in valid JSON with this structure:
{
  "score": <number 0-100>,
  "analysis": "<short paragraph explaining strengths and weaknesses>",
  "missing_points": ["point 1", "point 2", "..."]
}
Do NOT include any extra text outside the JSON.
"""


def build_llm_prompt(question: str, reference_answer: str, student_answer: str) -> str:
    return f"""
[QUESTION]
{question}

[REFERENCE ANSWER]
{reference_answer}

[STUDENT ANSWER]
{student_answer}

Compare the student's answer to the reference and respond following the instructions.
"""


def call_llm_evaluator(prompt: str) -> dict:
    """
    Calls the OpenAI API (new client, openai>=1.0.0) to evaluate the student's answer.
    Returns a dict with keys: score (float), analysis (str), missing_points (list).
    If OPENAI_API_KEY is not set, falls back to a dummy response.
    """
    # If there is no API key configured, return placeholder
    if client.api_key is None:
        return {
            "score": 75.0,
            "analysis": (
                "LLM evaluator is not configured (no OPENAI_API_KEY). "
                "This is a placeholder result."
            ),
            "missing_points": [],
        }

    try:
        response = client.chat.completions.create(
            model="gpt-4.1-mini",  # or any other model you have access to
            messages=[
                {"role": "system", "content": LLM_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=0.0,
            response_format={"type": "json_object"},  # ensure JSON-only output
        )

        content = response.choices[0].message.content
        data = json.loads(content)

        score = float(data.get("score", 0.0))
        analysis = data.get("analysis", "")
        missing_points = data.get("missing_points", [])

        return {
            "score": score,
            "analysis": analysis,
            "missing_points": missing_points,
        }

    except Exception as e:
        # Robust fallback for any error in the API
        return {
            "score": 0.0,
            "analysis": f"Error calling LLM evaluator: {e}",
            "missing_points": [],
        }


def evaluate_answer_llm(question: str, reference: str, student_answer: str) -> dict:
    prompt = build_llm_prompt(question, reference, student_answer)
    return call_llm_evaluator(prompt)


def evaluate_answer_llm(question: str, reference: str, student_answer: str) -> dict:
    """
    Uses an LLM as a judge for the student's answer.
    Returns a dict with:
    - score (0–100)
    - analysis (text explanation)
    """
    prompt = build_llm_prompt(question, reference, student_answer)
    llm_response = call_llm_evaluator(prompt)
    return llm_response


# ===============================
# 4. QUESTION SAMPLING & STATE
# ===============================

def sample_question(qa_list):
    return random.choice(qa_list)


if "current_qa" not in st.session_state:
    st.session_state.current_qa = None

if "history" not in st.session_state:
    st.session_state.history = []  # list of dicts


# ===============================
# 5. STREAMLIT UI
# ===============================

st.set_page_config(
    page_title="ML Q&A Evaluator",
    page_icon="🤖",
    layout="wide",
)

st.title("🤖 ML Concept Q&A Evaluator")
st.write(
    "This prototype asks you questions about Machine Learning concepts, "
    "collects your answer, and evaluates it automatically (ROUGE + keyword coverage). "
    "Optionally, it also shows a placeholder LLM-based evaluation."
)

with st.sidebar:
    st.header("Controls")
    if st.button("🔄 New random question"):
        st.session_state.current_qa = sample_question(qa_items)
        # Clear previous answer/result for clarity
        if "last_answer" in st.session_state:
            del st.session_state["last_answer"]
        if "last_eval_auto" in st.session_state:
            del st.session_state["last_eval_auto"]
        if "last_eval_llm" in st.session_state:
            del st.session_state["last_eval_llm"]

    if st.button("🧼 Reset session"):
        st.session_state.current_qa = None
        st.session_state.history = []
        if "last_answer" in st.session_state:
            del st.session_state["last_answer"]
        if "last_eval_auto" in st.session_state:
            del st.session_state["last_eval_auto"]
        if "last_eval_llm" in st.session_state:
            del st.session_state["last_eval_llm"]

    st.markdown("---")
    st.subheader("Session stats")
    st.write(f"Questions answered: **{len(st.session_state.history)}**")
    if st.session_state.history:
        avg_score = sum(h["evaluation"]["automatic"]["score"] for h in st.session_state.history) / len(st.session_state.history)
        st.write(f"Average automatic score: **{avg_score:.1f} / 100**")

    st.markdown("---")
    st.caption("Prototype for Assignment 11.00 – LLM Evaluator (Streamlit UI).")


# If there is no current question, sample one
if st.session_state.current_qa is None:
    st.session_state.current_qa = sample_question(qa_items)

current_qa = st.session_state.current_qa
question = current_qa["question"]
reference_answer = current_qa["answer"]

st.subheader("Current Question")
st.write(question)

st.markdown("### Your Answer")
default_text = st.session_state.get("last_answer", "")
student_answer = st.text_area(
    "Type your answer here:",
    value=default_text,
    height=160,
    placeholder="Write your explanation in your own words...",
)

col1, col2 = st.columns([1, 2])

with col1:
    submit_clicked = st.button("✅ Submit answer")

with col2:
    show_reference = st.checkbox("Show reference answer after evaluation")


if submit_clicked and student_answer.strip():
    # Store last answer
    st.session_state.last_answer = student_answer

    # 1) Automatic evaluation
    eval_auto = evaluate_answer(reference_answer, student_answer)

    # 2) LLM-based evaluation (stub, but structured)
    eval_llm = evaluate_answer_llm(question, reference_answer, student_answer)

    # Store last evals in session
    st.session_state.last_eval_auto = eval_auto
    st.session_state.last_eval_llm = eval_llm

    # Add to history
    st.session_state.history.append(
        {
            "question": question,
            "reference_answer": reference_answer,
            "student_answer": student_answer,
            "evaluation": {
                "automatic": eval_auto,
                "llm": eval_llm,
            },
        }
    )

# Display results if available
if "last_eval_auto" in st.session_state:
    eval_auto = st.session_state.last_eval_auto
    eval_llm = st.session_state.last_eval_llm

    st.markdown("## Evaluation Results")

    # Automatic evaluation
    st.markdown("### 🔍 Automatic Evaluation (ROUGE + Keywords)")
    st.write(f"**Score (0–100):** `{eval_auto['score']}`")
    st.write(
        textwrap.fill(eval_auto["explanation"], width=100)
    )

    # LLM-based evaluation
    st.markdown("### 🧠 LLM-based Evaluation (OpenAI Judge)")
    st.write(f"**LLM Score (0–100):** `{eval_llm['score']}`")
    st.write(textwrap.fill(eval_llm["analysis"], width=100))
    if eval_llm.get("missing_points"):
        st.write("**Key missing points (according to the LLM):**")
        st.write("- " + "\n- ".join(eval_llm["missing_points"]))

    # Reference answer (optional)
    if show_reference:
        st.markdown("### 📘 Reference Answer")
        st.write(textwrap.fill(reference_answer, width=100))
